"""Switch platform for smart_cover_automation.

Provides a Home Assistant switch entity that controls whether the smart cover automation
is enabled or disabled. This switch:

- Represents the global enabled/disabled state of the automation
- Persists its state in the integration's options (configuration)
- Triggers coordinator refresh when toggled to immediately apply state changes
- Inherits availability from the coordinator status

The switch state is stored in the config entry options, allowing it to persist
across Home Assistant restarts and integration reloads.
"""

from __future__ import annotations

from functools import cached_property
from typing import TYPE_CHECKING, Any

from homeassistant.components.switch import SwitchEntity, SwitchEntityDescription

from custom_components.smart_cover_automation.const import HA_OPTIONS

from .config import ConfKeys, resolve_entry
from .const import DOMAIN, INTEGRATION_NAME
from .entity import IntegrationEntity

if TYPE_CHECKING:
    from homeassistant.core import HomeAssistant
    from homeassistant.helpers.entity_platform import AddEntitiesCallback

    from .coordinator import DataUpdateCoordinator
    from .data import IntegrationConfigEntry

# Define switch entity descriptions for the platform
# The switch controls the global enabled/disabled state of the automation
ENTITY_DESCRIPTIONS = (
    SwitchEntityDescription(
        key=DOMAIN,
        name=f"{INTEGRATION_NAME}",
        icon="mdi:format-quote-close",
    ),
)


async def async_setup_entry(
    hass: HomeAssistant,  # noqa: ARG001 Unused function argument: `hass`
    entry: IntegrationConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the switch platform.

    Creates a single switch entity that controls the automation's enabled state.
    The switch is linked to the integration's coordinator for state management.
    """
    async_add_entities(
        IntegrationSwitch(
            coordinator=entry.runtime_data.coordinator,
            entity_description=entity_description,
        )
        for entity_description in ENTITY_DESCRIPTIONS
    )


class IntegrationSwitch(IntegrationEntity, SwitchEntity):  # pyright: ignore[reportIncompatibleVariableOverride]
    """Smart cover automation master enable/disable switch.

    This switch controls the global enabled state of the automation system.
    When turned off, the automation stops processing temperature and sun data
    and will not move any covers. When turned on, normal automation resumes.

    The switch state is persisted in the integration's configuration options,
    ensuring it survives Home Assistant restarts. State changes trigger an
    immediate coordinator refresh to apply the new setting.

    Inherits device grouping from IntegrationEntity and availability status
    from CoordinatorEntity via the inheritance chain.
    """

    def __init__(
        self,
        coordinator: DataUpdateCoordinator,
        entity_description: SwitchEntityDescription,
    ) -> None:
        """Initialize the automation control switch.

        Sets up the switch entity with coordinator integration and entity description.
        The unique ID is automatically generated by the parent IntegrationEntity class.
        """
        super().__init__(coordinator)
        self.entity_description = entity_description

    # Note: We inherit the 'available' property from IntegrationEntity/CoordinatorEntity
    # which provides the correct coordinator-based availability logic.
    # No override is needed since the default behavior is exactly what we want.

    @cached_property
    def is_on(self) -> bool:
        """Return whether the automation is currently enabled.

        Reads from the resolved settings to get the current enabled state.
        This reflects changes made through the integration's options flow.
        """
        resolved = resolve_entry(self.coordinator.config_entry)
        return resolved.enabled

    async def async_turn_on(self, **_: Any) -> None:
        """Enable the smart cover automation.

        Sets the enabled flag to True in the integration's options and triggers
        a coordinator refresh to immediately start automation processing.
        The state change persists across Home Assistant restarts.
        """
        # Persist enabled=True in options if available
        entry = self.coordinator.config_entry
        current = dict(getattr(entry, HA_OPTIONS, {}) or {})
        current[ConfKeys.ENABLED.value] = True
        await entry.async_set_options(current)  # type: ignore[attr-defined]
        await self.coordinator.async_request_refresh()

    async def async_turn_off(self, **_: Any) -> None:
        """Disable the smart cover automation.

        Sets the enabled flag to False in the integration's options and triggers
        a coordinator refresh to immediately stop automation processing.
        The state change persists across Home Assistant restarts.
        """
        entry = self.coordinator.config_entry
        current = dict(getattr(entry, HA_OPTIONS, {}) or {})
        current[ConfKeys.ENABLED.value] = False
        await entry.async_set_options(current)  # type: ignore[attr-defined]
        await self.coordinator.async_request_refresh()
