target-version = "py312"
line-length = 88

[lint]
# Only enable essential rules (no extended plugin rules)
select = ["E4", "E7", "E9", "F", "I"]
ignore = [
    "E501", # Line length handled by formatter/tests
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",    # assert in tests
    "SLF001",  # private-member-access in tests
    "PLR2004", # magic values in tests
    "B023",    # function-uses-loop-variable
    "TRY003",  # long exception messages
    "TRY301",  # raise within try
    "EM101",   # string literal in exception
    "EM102",   # f-string in exception
    "SIM102",  # collapsible if
    "TC003",   # type-checking import placement
]
