# Test-specific ruff configuration
target-version = "py313"

[lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "PT",   # flake8-pytest-style
]

ignore = [
    "S101",   # Use of `assert` detected (normal in tests)
    "E501",   # Line too long (tests can be longer)
    "PLR2004", # Magic value used in comparison
    "TRY003", # Avoid specifying long messages outside exception class
    "EM",     # Error message string literals
    "PT011",  # pytest.raises should specify expected exception
    "SLF001", # Private member access OK in tests
    "TRY301", # Abstract raise to inner function
    "SIM102", # Use single if instead of nested
    "B023",   # Function definition does not bind loop variable
]

[lint.per-file-ignores]
"tests/*" = [
    "S101",    # asserts allowed in tests
    "PLR2004", # Magic values OK in tests
    "SLF001",  # Private member access OK in tests
    "TRY003",  # Long exception messages OK in tests
    "EM101",   # String literals in exceptions OK
    "EM102",   # f-string literals in exceptions OK
    "TRY301",  # Abstract raise to inner function OK in tests
    "B023",    # Loop variable binding OK in tests
]
