name: Dependency Audit

on:
  schedule:
    - cron: '17 5 * * 2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruby-audit:
    name: Ruby Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: '3.3.4'
          bundler: none
          working-directory: '${{ github.workspace }}/docs'

      - name: Audit pinned Ruby dependencies
        working-directory: ./docs
        run: |
          gem install bundler-audit --no-document
          bundle-audit check --update