name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-ruff.txt
            requirements-test.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-ruff.txt -r requirements-test.txt

      - name: Run tests
        run: |
          python -m pytest -n auto tests/ -o addopts="--strict-markers --strict-config --cov=custom_components.smart_cover_automation --cov-report=term-missing --cov-report=xml --cov-fail-under=80"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: pip

      - name: Test integration loading
        shell: bash
        run: |
          python - <<'PY'
          import importlib.util
          from pathlib import Path

          const_path = Path('custom_components/smart_cover_automation/const.py')
          spec = importlib.util.spec_from_file_location('sca_const', const_path)
          const = importlib.util.module_from_spec(spec)
          assert spec and spec.loader
          spec.loader.exec_module(const)

          print(f"Integration {const.DOMAIN} module loaded successfully")
          print(f"Logger: {const.LOGGER.name}")
          PY

      - name: Validate manifest
        run: |
          python -c "
          import json
          with open('custom_components/smart_cover_automation/manifest.json') as f:
              manifest = json.load(f)
          required_keys = ['domain', 'name', 'version', 'documentation', 'issue_tracker']
          for key in required_keys:
              assert key in manifest, f'Missing required key: {key}'
          print('Manifest validation passed')
          "
