# This workflow runs tests and integration checks for the project.
# The name configured here shows up on the badge in the README.
#
# Note: To enable automatic coverage badge updates on protected branches:
# 1) create a fine-grained Personal Access Token (PAT) with the permission
#   'contents: read and write'
# 2) add your role (e.g., admin) as a bypass in the branch protection rule
# 3) add the PAT as a repository secret named 'PAT_TOKEN'.
# Without this, the badge will only update manually or the branch protection
# rules must allow GitHub Actions to bypass status checks for commits with [skip ci].
name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-test.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-test.txt

      - name: Run tests
        run: |
          python -m pytest -n auto tests/ -o addopts="--strict-markers --strict-config --cov=custom_components.smart_cover_automation --cov-report=term-missing --cov-report=xml --cov-report=json --cov-fail-under=80"

      - name: Generate coverage badge
        run: |
          python scripts/generate_coverage_badge.py

      - name: Commit coverage badge
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/badges/coverage.svg
          if git diff --staged --quiet; then
            echo "No changes to coverage badge"
          else
            git commit -m "Update coverage badge [skip ci]"
            git push
          fi
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
          cache: pip

      - name: Test integration loading
        shell: bash
        run: |
          python - <<'PY'
          import importlib.util
          from pathlib import Path

          const_path = Path('custom_components/smart_cover_automation/const.py')
          spec = importlib.util.spec_from_file_location('sca_const', const_path)
          const = importlib.util.module_from_spec(spec)
          assert spec and spec.loader
          spec.loader.exec_module(const)

          print(f"Integration {const.DOMAIN} module loaded successfully")
          print(f"Logger: {const.LOGGER.name}")
          PY

      - name: Validate manifest
        run: |
          python -c "
          import json
          with open('custom_components/smart_cover_automation/manifest.json') as f:
              manifest = json.load(f)
          required_keys = ['domain', 'name', 'version', 'documentation', 'issue_tracker']
          for key in required_keys:
              assert key in manifest, f'Missing required key: {key}'
          print('Manifest validation passed')
          "
