name: Validate

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@5752577ea7cc5aefb064b0b21432f18fe4d6ba90

  hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run HACS validation
        uses: hacs/action@dcb30e72781db3f207d5236b861172774ab0b485
        with:
          category: integration
